#ifndef DEFINES_H
#define DEFINES_H

#define KSILIT_VERSION "0.0.0"

#define KSILIT_LOG_FILE_NAME "ksilit.log"

#define KSILIT_JOTTER_COLUMN_NAME_NUMBER       0
#define KSILIT_JOTTER_COLUMN_NAME_TEXT         "Notes"
#define KSILIT_JOTTER_ACTION_ADD_SUB_NOTE_TEXT "Add Sub Note"

#define ERROR_OPENING_FILE 1

#endif // DEFINES_H
